apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-224622-ulx9-service
spec:
  selector:
    app: enterprise-system-224622-ulx9
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
